[package]
name = "space-invaders"
version = "0.1.0"
edition = "2021"
authors = ["Denis Salmanovich"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
rand = "0.8.5"
egui-macroquad = "0.12.0"
